import assert from 'node:assert/strict'
import { mkdirSync } from 'node:fs'
import { chromium } from 'playwright'
import { createServer } from 'vite'

const server = await createServer({ server: { host: '127.0.0.1', port: 0 } })
await server.listen()
const origin = `http://127.0.0.1:${server.httpServer.address().port}`
const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'msedge' } : {}) })
const output = process.env.BINHU_BROWSER_EVIDENCE_DIR || 'artifacts/floating-actions'
mkdirSync(output, { recursive: true })
try {
  for (const [width, height, dark] of [[1024, 640, false], [1280, 720, false], [1280, 960, true], [1680, 1050, false], [1920, 1080, true], [390, 844, false]]) {
    const context = await browser.newContext({ viewport: { width, height }, hasTouch: true })
    const page = await context.newPage()
    page.setDefaultTimeout(10_000)
    const errors = []
    page.on('pageerror', error => { errors.push(error.message); console.error(error.message) })
    await context.addInitScript(dark => localStorage.setItem('binhu-theme-mode', dark ? 'dark' : 'light'), dark)
    await context.route('**/*', route => {
      const url = new URL(route.request().url())
      if (url.origin !== origin) return route.abort()
      if (!url.pathname.startsWith('/api/')) return route.continue()
      const send = body => route.fulfill({ contentType: 'application/json', body: JSON.stringify(body) })
      if (url.pathname === '/api/app/bootstrap') return send({ environment: 'production', timezone: 'Asia/Shanghai', server_version: '0.30.26' })
      if (url.pathname === '/api/auth/me') return send({ user: { id: 1, username: 'synthetic-admin', display_name: '合成测试账号', role: 'super_admin', permissions: ['registry.property.view'], permission_groups: [], preferences: { theme_mode: dark ? 'dark' : 'light' } } })
      return send({ data: [], items: [], unavailable_sources: [], total: 0, active_count: 0, queued_count: 0, running_count: 0, attention_count: 0, match_status_counts: {}, unread_count: 0 })
    })
    await page.goto(`${origin}/registry`)
    const main = page.locator('.app-speed-dial__main')
    const history = page.locator('.my-task-history-float')
    const queue = page.locator('.admin-task-queue-float')
    await main.waitFor()
    await main.hover()
    await page.waitForTimeout(350)
    assert.equal(await page.getByRole('tooltip').count(), 0)
    const before = await main.boundingBox()
    await page.mouse.move(before.x + 26, before.y + 26)
    await page.mouse.down()
    await page.mouse.move(160, 180, { steps: 10 })
    await page.mouse.up()
    assert.equal(await main.getAttribute('aria-label'), '打开快捷功能')
    const after = await main.boundingBox()
    assert.ok(Math.abs(after.x - before.x) > 30)
    await main.click()
    await history.waitFor()
    await queue.waitFor()
    const checkBounds = async () => {
      for (const button of [main, history, queue]) {
        const rect = await button.boundingBox()
        assert.ok(rect && rect.x >= 0 && rect.y >= 0 && rect.x + rect.width <= page.viewportSize().width && rect.y + rect.height <= page.viewportSize().height, JSON.stringify(rect))
      }
    }
    // Moving an expanded group must neither activate nor lose its children.
    const current = await main.boundingBox()
    await page.mouse.move(current.x + 26, current.y + 26)
    await page.mouse.down()
    await page.mouse.move(-150, -150, { steps: 8 })
    await page.mouse.up()
    assert.equal(await main.getAttribute('aria-label'), '收起快捷功能')
    await page.waitForTimeout(200)
    await checkBounds()
    await history.hover()
    await page.waitForTimeout(350)
    assert.equal(await page.getByRole('tooltip').count(), 0)
    await history.click()
    await page.getByText('我的任务记录', { exact: true }).first().waitFor()
    await page.locator('.ant-drawer-open .ant-drawer-close').click()
    await page.locator('.ant-drawer-open').waitFor({ state: 'hidden' })
    await page.locator('.ant-drawer-mask').filter({ visible: true }).waitFor({ state: 'hidden' })
    await queue.click()
    await page.getByText('后台任务队列', { exact: true }).first().waitFor()
    await page.locator('.ant-drawer-open .ant-drawer-close').click()
    await page.locator('.ant-drawer-open').waitFor({ state: 'hidden' })
    await page.locator('.ant-drawer-mask').filter({ visible: true }).waitFor({ state: 'hidden' })
    // Genuine browser touch input exercises pointer capture and generated clicks.
    const cdp = await context.newCDPSession(page)
    const touchStart = await main.boundingBox()
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchStart.x + 26, y: touchStart.y + 26 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: width - 10, y: height - 10 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await page.waitForTimeout(200)
    assert.equal(await main.getAttribute('aria-label'), '收起快捷功能')
    const touchEnd = await main.boundingBox()
    assert.ok(touchEnd.x > touchStart.x + 100 && touchEnd.y > touchStart.y + 100, 'touch must actually move the ball')
    await checkBounds()
    await page.screenshot({ path: `${output}/${width}-${height}-${dark ? 'dark' : 'light'}.png` })
    await page.setViewportSize({ width: 390, height: 640 })
    await page.waitForTimeout(200)
    await checkBounds()
    const cancelStart = await main.boundingBox()
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: cancelStart.x + 26, y: cancelStart.y + 26 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 150, y: 250 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
    await page.waitForTimeout(100)
    assert.equal(await page.locator('.app-speed-dial.is-dragging').count(), 0)
    await main.click()
    assert.equal(await main.getAttribute('aria-label'), '打开快捷功能')
    await main.focus()
    await page.keyboard.press('Enter')
    assert.equal(await main.getAttribute('aria-label'), '收起快捷功能')
    assert.deepEqual(errors, [])
    console.log(JSON.stringify({ width, height, dark, result: 'passed' }))
    await context.close()
  }
} finally {
  await browser.close()
  await server.close()
}
