import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

import { apiErrorMessage } from '../src/api/client.ts'
import { canManageFullchainArchive } from '../src/utils/mobileTaskRouting.ts'

test('全链条归档错误展示兼容 FastAPI 校验数组且不渲染对象', () => {
  assert.equal(apiErrorMessage({ response: { data: { detail: '任务已变化' } } }, '失败'), '任务已变化')
  assert.equal(apiErrorMessage({ response: { data: { detail: [{ msg: '字段错误' }] } } }, '失败'), '字段错误')
  assert.equal(apiErrorMessage({ response: { data: { detail: { type: 'validation' } } } }, '失败'), '失败')
})

test('全链条归档面板只对全所范围的指定岗位和管理员开放', () => {
  assert.equal(canManageFullchainArchive('基础管控', 'user', [], ['police.dispatch.manage'], 'all', 'all'), true)
  assert.equal(canManageFullchainArchive('所队领导', 'user', [], ['police.dispatch.manage'], 'all', 'all'), true)
  assert.equal(canManageFullchainArchive('组员', 'super_admin', [], ['police.dispatch.manage'], 'all', 'all'), true)
  assert.equal(canManageFullchainArchive('组员', 'user', [], ['police.dispatch.manage'], 'all', 'all'), false)
  assert.equal(canManageFullchainArchive('基础管控', 'user', [], ['police.dispatch.manage'], 'own_department', 'all'), false)
})

test('归档候选使用后端分页、防竞态和跨页选择，历史展示安全逐条状态', () => {
  const panel = readFileSync(new URL('../src/components/FullchainArchivePanel.tsx', import.meta.url), 'utf8')
  const rawPanel = readFileSync(new URL('../src/components/FullchainPoliceRawPanel.tsx', import.meta.url), 'utf8')
  const client = readFileSync(new URL('../src/api/client.ts', import.meta.url), 'utf8')
  const upload = readFileSync(new URL('../src/pages/DataUploadCenter.tsx', import.meta.url), 'utf8')
  const tasks = readFileSync(new URL('../src/pages/MobileTaskList.tsx', import.meta.url), 'utf8')
  const taskDetail = readFileSync(new URL('../src/pages/MobileTaskDetail.tsx', import.meta.url), 'utf8')

  assert.match(panel, /candidateRequestId/)
  assert.match(panel, /page_size: pageSize/)
  assert.match(panel, /preserveSelectedRowKeys: true/)
  assert.match(panel, /onSelectAll: checked =>/)
  assert.match(panel, /全选所有可选数据/)
  assert.match(client, /candidates\/selection/)
  assert.match(panel, /showTotal: value => `共 \$\{value\} 条`/)
  assert.match(panel, /detail\.status !== 'success' \|\| detail\.reconcile_state\.startsWith\('reconciled_'\)/)
  assert.match(panel, /external_delete_state/)
  assert.match(panel, /title: '移出当前任务池'/)
  assert.match(panel, /title: '平台归档'/)
  assert.match(panel, /title: '平台对账'/)
  assert.match(panel, /title: '失败阶段'/)
  assert.match(panel, /value === 'success'/)
  assert.match(panel, /\? '已完成'/)
  assert.match(panel, /reconciled_by_sync: '已由历史同步归档并完成对账'/)
  assert.match(panel, /external_delete_outcome_unknown: '历史外部移除结果不确定，禁止自动重试'/)
  assert.match(panel, /registration_archive_evidence_changed: '居住证确认、房屋或来源状态已变化，当前任务未归档'/)
  assert.doesNotMatch(panel, /腾讯整行删除|腾讯行未删除/)
  assert.match(panel, /registration_evidence: '登记确认复核'/)
  assert.match(panel, /label: '已登记确认'/)
  assert.match(panel, /title: '已登记确认时间'/)
  assert.match(panel, /title: '归档保留期至'/)
  assert.match(client, /platform_archive_state:/)
  assert.match(client, /reconcile_state:/)
  assert.match(panel, /apiErrorMessage/)
  assert.match(client, /items: Array<\{/)
  assert.doesNotMatch(upload, /FullchainPoliceRawPanel/)
  assert.doesNotMatch(client, /previewFullchainPoliceRaw/)
  assert.doesNotMatch(client, /confirmFullchainPoliceRaw/)
  assert.match(rawPanel, /历史公安网原始数据（只读）/)
  assert.match(rawPanel, /本区文件不会影响候选结果/)
  assert.doesNotMatch(rawPanel, /Dragger|确认作为当前比对数据|预览原始数据/)
  assert.match(panel, /parserType === '全链条' && <FullchainPoliceRawPanel enabled \/>/)
  assert.match(client, /archive_available_at\?: string \| null/)
  assert.match(client, /archive_ready\?: boolean/)
  assert.match(taskDetail, /label: '已登记确认时间'/)
  assert.match(taskDetail, /已满足完整 24 小时保留期/)
  assert.match(taskDetail, /formatSystemTime\(registrationLink\.archive_available_at\)/)
  assert.match(tasks, /canUseFullchainArchive && <FullchainArchivePanel parserType=\{parserType\} \/>/)
})
