import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

test('Rete 任务图使用真实任务、系统依赖和超级管理员代入视角', () => {
  const page = readFileSync(new URL('../src/pages/ReteTaskFlowLab.tsx', import.meta.url), 'utf8')
  const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
  const client = readFileSync(new URL('../src/api/client.ts', import.meta.url), 'utf8')
  const detail = readFileSync(new URL('../src/pages/MobileTaskDetail.tsx', import.meta.url), 'utf8')
  const oldLab = readFileSync(new URL('../src/pages/TaskFlowLab.tsx', import.meta.url), 'utf8')
  const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))

  assert.equal(pkg.dependencies.rete.startsWith('^2.'), true)
  assert.equal(pkg.dependencies['rete-react-plugin'].startsWith('^2.'), true)
  assert.equal(pkg.dependencies['rete-auto-arrange-plugin'].startsWith('^2.'), true)
  assert.match(page, /AutoArrangePlugin/)
  assert.match(page, /layoutIndependentNodes/)
  assert.match(page, /const columns = 4/)
  assert.match(page, /Math\.floor\(slot \/ columns\)/)
  assert.match(page, /const gridStartY = connectedBottom > 0/)
  assert.match(page, /const occupied = new Set/)
  assert.match(page, /'elk\.algorithm': 'layered'/)
  assert.match(page, /TaskInstanceNode/)
  assert.match(page, /TaskDependencyConnection/)
  assert.match(page, /searchTaskGraph/)
  assert.match(page, /getTaskGraphOptions/)
  assert.match(page, /previewTaskGraphBackfill/)
  assert.match(page, /runTaskGraphBackfill/)
  assert.match(page, /updateTaskGraphConfig/)
  assert.match(page, /网格员视角/)
  assert.match(page, /基础管控视角/)
  assert.match(page, /已完成\/历史/)
  assert.match(page, /只读查看/)
  assert.match(page, /查看等待/)
  assert.match(page, /继续加载各类独立任务/)
  assert.doesNotMatch(page, /FLOW_NODES/)
  assert.match(client, /export interface TaskGraphNode/)
  assert.match(client, /\/task-graph\/search/)
  assert.match(page, /task_types: taskType === 'all'/)
  assert.match(detail, /searchParams\.get\('readonly'\) === '1'/)
  assert.match(detail, /data\.dependency_blocked/)
  assert.match(detail, /任务图只读协作视图/)
  assert.match(detail, /等待前置任务/)
  assert.match(app, /path="\/task-flow-rete-lab"/)
  assert.match(app, /ProtectedRoute requireRole="super_admin"/)
  assert.match(oldLab, /试用 Rete\.js 工作流/)
})
