import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { createServer } from 'vite'
import { mkdirSync } from 'node:fs'
const server = await createServer({ server: { host: '127.0.0.1', port: 5199, strictPort: true } }); await server.listen()
const origin = 'http://127.0.0.1:5199'; const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'msedge' } : {}) })
try {
 for (const [width, dark] of [[1280, false], [390, false], [1280, true], [390, true]]) {
  const context = await browser.newContext({ viewport: { width, height: 960 } }); const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message))
  let revision = 1, delay = 0, fail = ''; let values = { 姓名: '虚构输入任务', 核查人: '虚构核查员', 核查结果: '无法核实', 现住址: '虚构原地址', 二次反馈: '', 备注: '' }; const writes = []
  const detail = () => ({ task: {}, writeback_enabled: true, workflow: { result_field: '核查结果', secondary_fields: ['二次反馈'], analysis_fields: [], columns: [] }, sources: [{ id: 1, revision, row_key: 'fixture:1', source_available: true, values: { ...values }, editable_fields: ['核查结果', '现住址', '二次反馈', '备注'], cell_meta: { 核查结果: { type: 'select', options: [{ text: '无法核实' }, { text: '待登记' }] } } }] })
  await context.route('**/*', async route => { const url = new URL(route.request().url()); if (url.origin !== origin) return route.abort(); if (!url.pathname.startsWith('/api/')) return route.continue(); const send = (body, status = 200) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) }); if (url.pathname.endsWith('/inline-editors')) return send({ items: { 'fixture:1': { available: true, detail: detail() } } }); if (url.pathname.includes('source-rows') && route.request().method() === 'PATCH') { const body = route.request().postDataJSON(); writes.push(body); const failure = fail; fail = ''; await new Promise(r => setTimeout(r, delay)); if (failure === 'conflict') { values['二次反馈'] = '服务器新增线索'; revision++; return send({ detail: { code: 'task_revision_conflict', columns: ['二次反馈'], current_values: { 二次反馈: values['二次反馈'] }, current_revision: revision } }, 409) }; if (failure === 'busy') return send({ detail: { code: 'task_save_busy' } }, 409); assert.equal(body.expected_revision, revision); Object.assign(values, body.changes); revision++; return send({ values: { ...values }, revision, message: '已保存' }) }; if (url.pathname.endsWith('/registry/properties/search')) return send({ data: [] }); return send({ data: [], timezone: 'Asia/Shanghai' }) })
  const field = name => page.locator(`[data-editor-field="${name}"]`); const feedback = field('二次反馈').locator('textarea'); const address = () => field('现住址').locator('textarea, input:not([type=hidden])').first(); const waitWrites = async n => { for (let i = 0; i < 80 && writes.length < n; i++) await page.waitForTimeout(50); assert.equal(writes.length, n) }
  await page.goto(`${origin}/tests/taskAutosave.fixture.html${dark ? '?dark' : ''}`); await feedback.waitFor(); await feedback.scrollIntoViewIfNeeded(); await feedback.focus()
  await feedback.fill('前缀'); await feedback.dispatchEvent('compositionstart'); await feedback.fill('前缀zhongwen'); await page.waitForTimeout(1200); assert.equal(writes.length, 0); await feedback.fill('前缀中文'); await feedback.dispatchEvent('compositionend', { data: '中文' }); await page.waitForTimeout(300); assert.equal(writes.length, 0); await feedback.blur(); await waitWrites(1); assert.equal(writes[0].changes['二次反馈'], '前缀中文')
  delay = 300; await feedback.fill('第一版'); await page.waitForTimeout(150); await feedback.fill('第二版'); await page.waitForTimeout(9500); assert.equal(writes.length, 1); await page.waitForTimeout(1000); await waitWrites(2); assert.equal(writes[1].changes['二次反馈'], '第二版'); assert.equal(await feedback.isEnabled(), true)
  await feedback.fill('跨字段反馈'); await address().fill('虚构新住址'); await feedback.focus(); await feedback.blur(); await waitWrites(3); assert.equal(writes[2].changes['二次反馈'], '跨字段反馈'); await feedback.focus(); await feedback.blur(); await page.waitForTimeout(200); assert.equal(writes.length, 3)
  delay = 500; await feedback.fill('请求中的旧草稿'); await feedback.blur(); await feedback.fill('请求完成后的最新草稿'); await waitWrites(4); await page.waitForTimeout(1200); assert.equal(await feedback.inputValue(), '请求完成后的最新草稿'); await feedback.blur(); await waitWrites(5); assert.equal(values['二次反馈'], '请求完成后的最新草稿')
  delay = 0; fail = 'conflict'; await feedback.fill('保留的冲突草稿'); await feedback.blur(); await waitWrites(6); await field('二次反馈').getByRole('button', { name: '核对后重试' }).click(); await page.getByText('服务器当前值：服务器新增线索').waitFor(); await page.getByRole('button', { name: '保留草稿并重试' }).click(); await waitWrites(7); await field('二次反馈').getByText('已保存', { exact: true }).waitFor(); assert.equal(values['二次反馈'], '保留的冲突草稿')
  fail = 'busy'; await feedback.fill('失败后保留'); await feedback.blur(); await waitWrites(8); await field('二次反馈').getByText('未保存，草稿已保留', { exact: true }).waitFor(); assert.equal(await feedback.inputValue(), '失败后保留'); await field('二次反馈').getByRole('button', { name: '重试保存' }).click(); await waitWrites(9); await field('二次反馈').getByText('已保存', { exact: true }).waitFor(); assert.equal(values['二次反馈'], '失败后保留')
  delay = 600; await feedback.focus(); await feedback.fill('布局稳定'); await feedback.evaluate(element => { window.positions = []; window.sample = true; const frame = () => { if (!window.sample) return; window.positions.push([element.getBoundingClientRect().y, document.activeElement === element, element.disabled]); requestAnimationFrame(frame) }; frame() }); await feedback.blur(); await waitWrites(10); await page.waitForTimeout(100); const frames = await feedback.evaluate(() => { window.sample = false; return window.positions }); assert.ok(frames.every(frame => !frame[2])); assert.ok(Math.max(...frames.map(frame => frame[0])) - Math.min(...frames.map(frame => frame[0])) <= 1)
  assert.deepEqual(errors, []); mkdirSync('artifacts/autosave', { recursive: true }); await page.screenshot({ path: `artifacts/autosave/${width}-${dark ? 'dark' : 'light'}.png`, fullPage: true }); console.log(JSON.stringify({ width, dark, writes: writes.length, result: 'passed' })); await context.close()
 }
} finally { await browser.close(); await server.close() }
